<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf8" />
    <title>Installation</title>
    <style type="text/css">
        table, .table {
            width:900px;
            background: #f6f6f6;
            padding:10px;
            margin:0 auto;
        }

        .yes{
            color:green;
            font-weight:bold
        }
        .red{
            color:red;

        }
    </style>
</head>
<body>